//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentDev.MethodUsedBy {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentDev.MethodUsedBy.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アセンブリ ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssemblyDir {
            get {
                return ResourceManager.GetString("AssemblyDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ** パラメタ **
        ///アセンブリ ディレクトリ : {0}
        ///キーワード : {1}
        ///※ キーワードはカンマ区切りで複数指定します。
        ///************** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00001 {
            get {
                return ResourceManager.GetString("MSG00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00002 {
            get {
                return ResourceManager.GetString("MSG00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメタおよび設定の検証中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00003 {
            get {
                return ResourceManager.GetString("MSG00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   呼び出し階層を解析中...
        ///※ これは時間がかかることがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00004 {
            get {
                return ResourceManager.GetString("MSG00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュから解析結果を読み込み中...
        ///※ これは時間がかかることがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00005 {
            get {
                return ResourceManager.GetString("MSG00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の指定に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00006 {
            get {
                return ResourceManager.GetString("MSG00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のメソッドの定義を検索しましたが見つかりませんでした。このメソッドの解析はスキップされます。
        ///メソッド名 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00007 {
            get {
                return ResourceManager.GetString("MSG00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のメソッドはシグネチャのみで実装がありません。このメソッドの解析はスキップされます。
        ///メソッド名 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00008 {
            get {
                return ResourceManager.GetString("MSG00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   呼び出し階層の最上位メソッドを特定中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00009 {
            get {
                return ResourceManager.GetString("MSG00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果をファイルへ出力中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00010 {
            get {
                return ResourceManager.GetString("MSG00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュファイルを保存中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00011 {
            get {
                return ResourceManager.GetString("MSG00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存済みキャッシュを読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00012 {
            get {
                return ResourceManager.GetString("MSG00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理時間 : {0}ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00013 {
            get {
                return ResourceManager.GetString("MSG00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [解析打ち切り] {0}
        ///{1}※ 呼び出し階層の深さが設定値(MaxCalltreeDepth)を超えたため。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG00014 {
            get {
                return ResourceManager.GetString("MSG00014", resourceCulture);
            }
        }
    }
}
